name: Android Lint and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint checks
        run: ./gradlew lint

      - name: Run unit tests
        run: ./gradlew test
